# .github/workflows/main.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data collection
      run: |
        python data_collection.py
        python energy_data_collection.py

    - name: Run data cleaning
      run: |
        python data_cleaning.py

    - name: Train model
      run: |
        python model_development.py

    - name: Test model
      run: |
        python model_testing.py

    - name: Run Flask application (for local testing)
      run: |
        nohup python app.py &
        sleep 10
        curl http://127.0.0.1:5000/predict -d '{"temperature": 25, "humidity": 50, "wind_speed": 5, "historical_demand": 1000}' -H "Content-Type: application/json"

    - name: Run Dash dashboard (for local testing)
      run: |
        nohup python dashboard.py &
        sleep 10
        curl http://127.0.0.1:8050

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pip install awsebcli
        eb init -p python-3.7 energy-optimization --region us-west-2
        eb deploy

            - name: Install flake8
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .

